### ISSUE TITLE
Ubuntu 14.04 docker error

### ISSUE THREAD

**Issue by daleus** [trick77/dockerflix#1]
root@buff:~/dockerflix# ./build.sh
flag provided but not defined: -f

Same output also when running "docker build --no-cache=true -f dockerflix.us -t trick77/dockerflix ."

Ubuntu 14.04 vps, completely updated. Package installed is docker-io as lxc-docker exists no more.

**Comment by daleus** [comment]
Nevermind - I am an asshat. Docker needs updating to or beyond 1.4, I had 32bit OS installed, and 1.4+ only works on 64bit. Feel free to leave my idiot posting here for other idiots to realise they are also idiots.

**Comment by trick77** [comment]
Thanks ;-)
