### ISSUE TITLE
How do we add extra services in sniproxy.conf?

### ISSUE THREAD

**Issue by steveharman** [trick77/dockerflix#10]
Hi,

I'm all up & running - great stuff, thanks.

Now I need to add some additional services (wibble.com, wobble.com etc) and am a bit new to navigating Docker.  It seems we need to edit sniproxy.conf and a bit of digging around finds me several instances of that file preceded by, presumably, Docker IDs?  For example:

./var/lib/docker/aufs/diff/63400d1690fc9344b47ac9bb24b0681046c54566b8873be894e4997895d04795/etc/sniproxy/sniproxy.conf

I've tried editing one of those .confs, adding my new sites in the 'table' block, saving & restarting dockerflix, but when I use the python script to generate my Dnsmasq config all I get are the existing DNS entries which came with the default install.

Any help would be much appreciated.  A Python script that added new services & rebooted docker would be super-cool! "python ./addservice-conf.py --servicename mydomain.com" ?   :-)  

Cheers,

Steve

**Comment by steveharman** [comment]
OK so I've found the /config directory in /dockerflix. 

Thought I'd cracked it by editing /dockerflix/config/us-dockerflix-sniproxy.conf - add in my new domains, stop the existing dockerflix container, re-run the dockerflix build script, start the new container, run ./gendns-conf.py --remoteip [my IP] and....    No luck, I'm still stuck with the same domains in the default dockerflix install despite us-dockerflix-sniproxy.conf containing an updated list of services.

Now I really am out of ideas - how **do** we add new services?  The dockerflix Readme says 't's now so much easier to add support for a service' - but it's got me beaten.

Thanks,

Steve

**Comment by trick77** [comment]
Your editing workflow doesn't sound wrong to me but I can't say where it goes wrong. I just added support for NBC Sports video clips. Since I don't have a subscription I can't tell if live content works as well but at least the video clips are playing just fine.

**Comment by steveharman** [comment]
Thanks for the feedback.  I'm still not having a lot of luck. Running my NBC Sports Live Extra client software (Kodi) through a local proxy for investigation purposes I get the following hosts requested when attempting to open & stream:

address=/ipinfo.io/{IP}
address=/nbcsports.com/{IP}
address=/whatismyip.org/{IP}
address=/nbcstreameast.nbcsports.com/{IP}
address=/stream.nbcsports.com/{IP}
address=/as.dtvce.com/{IP}
address=/sp.auth.adobe.com/{IP}
address=/ldp.dtvce.com/{IP}
address=/hdliveextra­pmd.edgesuite.net/{IP}
address=/tvegolf­i.akamaihd.net/{IP}
address=/hdliveextra­vh.akamaihd.net/{IP}
address=/link.theplatform.com/{IP}
address=/sprtvod3­vh.akamaihd.net/{IP}
address=/as.gg.dtvce.com/{IP}
address=/stream.nbcsports.com.edgesuite.net/{IP}
address=/a1428.b.akamai.net/{IP}
address=/a1856.g2.akamai.net/{IP}
address=/sp.adobepass.com/{IP}
address=/nbcstreameast.nbcsports.com.edgesuite.net/{IP}
address=/a1123.g2.akamai.net/{IP}
address=/a689.w23.akamai.net/{IP}
address=/a176.w16.akamai.net/{IP}

Although I still can't get streams to playback, even with a valid subscription which I can get streaming OK through a commercial dns proxy.

Happy to test anything out with my subscription if it helps?

Thanks again,

Steve

**Comment by GhostlyCrowd** [comment]
The only way i have been able to add stuff and get it working, is to edit the config in the docker build folder. then run "docker stop dockerflix ; docker rm dockerflix ; ./build.sh && docker run -d -p 80:80 -p 443:443 --restart=always --name dockerflix trick77/dockerflix" to rebuild the whole thing. then it configs the sites I've added in the  /dockerflix/config/ directory

**Comment by random-robbie** [comment]
alter the bottom of the table to 

```
table {
    .* *
}
```

this proxys any request and seeing as all domains are in the dnsmasq file it should proxy any that point to the IP of the sniproxy.

**Comment by steveharman** [comment]
That's a great tip, thanks.  

For testing purposes is there a similar wildcard method for dnsmasq?  So I could have dnsmasq send EVERY request on my LAN to the sniporxy which would be configured to proxy everything ( ^^ ).  Then if I get things working I can start fine-tuning precisely what I need and only proxy that.

Thanks again.

**Comment by random-robbie** [comment]
there isnt unfortunately.

you could install squid proxy and test it to confirm the ip of your VPS is fine.

https://gist.github.com/txt3rob/9e054b61fda3f33f1360

is a config file to use port 9961 and be fully anon.

if your links dont work when you use this then there aint much you can do about it.
