### ISSUE TITLE
Last build installation problem

### ISSUE THREAD

**Issue by psanzm** [trick77/dockerflix#17]
Hi, first at all thanks for your amazing work, it's just what i was looking for.

I running an VPS in DigitalOcean with Ubuntu 14.04.3 and when I build the docker get this error:

root@smarty:~/dockerflix# ./build.sh
Sending build context to Docker daemon 119.3 kB
Sending build context to Docker daemon
Step 0 : FROM phusion/baseimage:0.9.16
 ---> 5a14c1498ff4
Step 1 : MAINTAINER trick77 jan@trick77.com https://trick77.com/
 ---> Running in f07f15c8bc6d
 ---> 17575ff2290f
Removing intermediate container f07f15c8bc6d
Step 2 : RUN apt-get -qq update
 ---> Running in 9026ddf7cba8
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/InRelease

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Some index files failed to download. They have been ignored, or old ones used instead.
 ---> bcacd78e0e0d
Removing intermediate container 9026ddf7cba8
Step 3 : RUN apt-get -y install python-software-properties     && add-apt-repository ppa:dlundquist/sniproxy     && apt-get update && apt-get -y install sniproxy
 ---> Running in 30e163607a0b
Reading package lists...
Building dependency tree...
Reading state information...
Package python-software-properties is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  software-properties-common

E: Package 'python-software-properties' has no installation candidate
The command '/bin/sh -c apt-get -y install python-software-properties     && add-apt-repository ppa:dlundquist/sniproxy     && apt-get update && apt-get -y install sniproxy' returned a non-zero code: 100

The error seems the package python-software-properties but if I run in the VPS "apt-cache search python-software-properties" I have no problem finding that.

Any clue about how to fix this?

Thanks in advance for your response,

Regards, Pedro.

**Comment by trick77** [comment]
Thanks!
Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg Could not resolve 'archive.ubuntu.com'

This could have been a temporary problem in the VPS or there's a problem with name the DNS in the VPS. It's not related to Dockerflix. You could ask DO for support if you don't know how to solve it.

**Comment by psanzm** [comment]
Hi trick and thanks for reply back so quickly!

The VPS resolves correctly 

root@smarty:~# nslookup archive.ubuntu.com
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   archive.ubuntu.com
Address: 91.189.91.14
Name:   archive.ubuntu.com
Address: 91.189.91.13
Name:   archive.ubuntu.com
Address: 91.189.92.200
Name:   archive.ubuntu.com
Address: 91.189.91.15
Name:   archive.ubuntu.com
Address: 91.189.91.23
Name:   archive.ubuntu.com
Address: 91.189.92.201
Name:   archive.ubuntu.com
Address: 91.189.91.24
Name:   archive.ubuntu.com
Address: 91.189.88.149

And the command "apt-get -qq update" runs without problems, it't seems to be only in the docker contanier during the building process.

Again, thanks for your reply.

**Comment by trick77** [comment]
It's because Docker can't reach your local DNS server.

**Comment by psanzm** [comment]
Ok, i will investigate further because the local dns server is working without problems. I use myself as dns server in my local pc.

I'll keep you updated if I find something else.

**Comment by trick77** [comment]
The Docker container has its own network and is connected to your VPS's network using a bridge. Localhost in the container != localhost in the VPS.
