### ISSUE TITLE
Ubuntu 14.04 image not found

### ISSUE THREAD

**Issue by warbux** [trick77/dockerflix#18]
I am getting the following error. Do you have any ideas as to what is wrong?

docker run -d -p 80:80 -p 443:443 --restart=always --name dockerflix trick77/dockerflix
Unable to find image 'trick77/dockerflix:latest' locally
Pulling repository trick77/dockerflix
Error: image trick77/dockerflix:latest not found

**Comment by trick77** [comment]
Looks like you didn't build the image properly.

**Comment by warbux** [comment]
Sorry I meant bbci.co.uk and yes I am sure

**Comment by trick77** [comment]
Looks like you're commenting on the wrong issue.

**Comment by warbux** [comment]
Sorry replied to wrong email.

.  https://github.com/notifications/beacon/AOeRrh0D8C_Xaa3fphdxoJ47C3UD_HHbks5o81t8gaJpZM4GQ0Rl.gif
