### ISSUE TITLE
bbc.co.uk not working

### ISSUE THREAD

**Issue by warbux** [trick77/dockerflix#19]
I think bbc.co.uk added bbc1.co.uk recently because it no longer works but the other sites do.

**Comment by trick77** [comment]
You sure about that?

drfalken@wopr:~$ ping bbc1.co.uk
ping: unknown host bbc1.co.uk

**Comment by Dave-Cox** [comment]
I tested it and he is correct. it appears that you need bbci.co.uk and possibly vod-hds-uk-live.edgesuite.net

**Comment by trick77** [comment]
Fixed. Thanks for reporting!
