### ISSUE TITLE
Port

### ISSUE THREAD

**Issue by saiedgerami** [trick77/dockerflix#21]
I like to free up ports 80 and 443 on the VPS (not the container). Three questions:
- Can DNSMask send the request to a different port?
- DockerFlix won't notice the change, if I route back to 80/443 on the docker run commend, will it?
- Can this change let me run netproxy (tunlr-style-dns-unblocking) on the same VPS?

**Comment by trick77** [comment]
I'm not saying that this isn't possible but it's not worth the hassle IMO. Just FYI: DNS has nothing to do with ports.
