### ISSUE TITLE
Issue running apt-get update

### ISSUE THREAD

**Issue by mdsEu** [trick77/dockerflix#22]
Hello, 

Trying to install it, but, seems to be running an issue running apt-get update:

Ign http://get.docker.io docker Release  
Ign http://get.docker.io docker/main TranslationIndex  
Err http://get.docker.io docker/main amd64 Packages  
  Undetermined Error [IP: 54.175.177.80 80]
Err http://get.docker.io docker/main i386 Packages  
  Undetermined Error [IP: 54.175.177.80 80]
Ign http://get.docker.io docker/main Translation-en_US  
Ign http://get.docker.io docker/main Translation-en  
W: Failed to fetch http://get.docker.io/ubuntu/dists/docker/main/binary-amd64/Packages  Undetermined Error [IP: 54.175.177.80 80]             

W: Failed to fetch http://get.docker.io/ubuntu/dists/docker/main/binary-i386/Packages  Undetermined Error [IP: 54.175.177.80 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.

Any ideas? Thanks!

**Comment by random-robbie** [comment]
what OS dude?

**Comment by random-robbie** [comment]
http://docs.docker.com/v1.8/installation/ubuntulinux/  for ubuntu

**Comment by mdsEu** [comment]
Hey, thanks for your response.

It’s running Ubuntu 12.04.5 LTS.

Thanks!

Lucas Cardona

**Comment by mdsEu** [comment]
Thanks, Robbie. I was able to set everything up.  I would assume I’d setup the public IP of the VPS as the DNS server on my computer? It doesn’t seem to resolve… I’m sure I’m missing something!

The IP is 54.183.252.218, not sure what the issue may be?

Thanks again!

Lucas Cardona
