### ISSUE TITLE
Can't get working on kernel 2.6

### ISSUE THREAD

**Issue by choldi** [trick77/dockerflix#23]
Can you help me getting work in kernel 2.6 (Debian 7 x64)?
I got a VPS and linux kernel 3.1 is not supported.

Thanks,
Jordi

**Comment by trick77** [comment]
Is this OpenVZ? If yes, I don't think Docker runs on top of OpenVZ.

**Comment by choldi** [comment]
Yes, is openvz. Any guide to run the proxy manually it would be appreciated (without docket)

-----Mensaje original-----
De: "trick77" notifications@github.com
Enviado: ‎22/‎11/‎2015 22:52
Para: "trick77/dockerflix" dockerflix@noreply.github.com
CC: "choldi" jordias@gmail.com
Asunto: Re: [dockerflix] Can't get working on kernel 2.6 (#23)

Is this OpenVZ? If yes, I don't think Docker runs on top of OpenVZ.

**Comment by trick77** [comment]
Get a KVM VPS ;-) No seriously... OpenVZ is crap for new stuff like Docker.

**Comment by choldi** [comment]
No cheap KVM :-( 
Anyway, thank you for your work, for your quick answer and for your time

Jordi 

-----Mensaje original-----
De: "trick77" notifications@github.com
Enviado: ‎22/‎11/‎2015 23:06
Para: "trick77/dockerflix" dockerflix@noreply.github.com
CC: "choldi" jordias@gmail.com
Asunto: Re: [dockerflix] Can't get working on kernel 2.6 (#23)

Get a KVM VPS ;-) No seriously... OpenVZ is crap for new stuff like Docker.
