### ISSUE TITLE
is it possible to run on port other than 443/80?

### ISSUE THREAD

**Issue by ralyodio** [trick77/dockerflix#26]
I have a web server already running, I would like to run my main DNS server on the same server and have two other geo located DNS sub-servers in UK and US.

I don't want to use port 80 for this if possible.

**Comment by trick77** [comment]
You can run the service on any port you like but browsers and other client devices probably want to talk to port 80 and 443 on the server.

**Comment by ralyodio** [comment]
what does browser have to do with it? I thought I just enter my custom DNS servers on my operating system.
