### ISSUE TITLE
More information around Chromecast?

### ISSUE THREAD

**Issue by victorhooi** [trick77/dockerflix#27]
The README mentions that Chromecast devices hard-code the DNS address.

I know for a normal DNS service (like say, Getflix), you can just use DNAT to re-write any DNS requests to Google's DNS to Getflix's DNS address.

However, using your approach, how would this work? You mention using iptables to reroute these requests - can you give any more information?

Do you mean re-write the HTTP/HTTPS requests? Or something else?

**Comment by aaronbrooks-gh** [comment]
You want a firewall such as pfsense that will redirect all traffic bound for port 53 from those devices to your own DNS server, outlined here: https://mateh.id.au/2014/08/stream-netflix-chromecast-using-pfsense/
