### ISSUE TITLE
Dockerflix works, but Netflix still recognizes, that I am using a proxy

### ISSUE THREAD

**Issue by g0r3** [trick77/dockerflix#32]
Hello,

after being scared away from unblock-us a few weeks ago, because Netflix decided to block it, I've decided to help myself and setup a server for myself, hoping, that Netflix doesn't block me, if I use a solution, that isn't used by everyone else. I decided to set up my own smart dns server, found dockerflix, rented a server from Virmach (virmach.com) and set it up for dockerflix.

For now it seems to work, at least, if I try it with with the suggested page http://ipinfo.io/. But unfortunately it still is being recoginzed by Netflix. Any suggestions, what might be wrong? Maybe virmach is also blocked by Netflix? Can you suggest another hoster? 

Thanks!

**Comment by trick77** [comment]
It's easy for Netflix to detect VPN usage, hopping VPN providers is not the solution. Unless you're using residendial IP addresses you can't beat them in this cat and mouse game.

**Comment by g0r3** [comment]
So you are saying, that Dockerflix doesn't work for the moment?

**Comment by trick77** [comment]
Dude, it's not a Dockerflix problem. It's a NETFLIX Problem.

**Comment by g0r3** [comment]
That was not my question. My question was, if I can get Netflix US with Dockerflix right now.

**Comment by trick77** [comment]
You can, if you're using one of the providers that have not been blacklisted by Netflix.

**Comment by g0r3** [comment]
Can you name me one of these? That would be awesome

**Comment by trick77** [comment]
Yeah right, in a public place like this.

**Comment by g0r3** [comment]
Would you mail it to me, if I give you an email address?
