### ISSUE TITLE
lame question

### ISSUE THREAD

**Issue by pueblo23** [trick77/dockerflix#33]
Hello! sorry for probably lame question. I have some linux basics so i was able to setup VPS server etc but i can not pass the step 

docker-compose up -d uk

probably i dont know how to

Clone this Github repository and build/run the Dockerflix container

correctly..

I did this

git clone --bare https://github.com/trick77/dockerflix.git

but docker-compose up -d uk is telling me 

ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

```
    Supported filenames: docker-compose.yml, docker-compose.yaml
```

what am I missing please? what directory shall i be in ??

**Comment by trick77** [comment]
git clone https://github.com/trick77/dockerflix.git 
without --bare might help

**Comment by pueblo23** [comment]
thanks! that helped :) 
i did 
sudo docker-compose start
it has started, but using my vps IP as DNS makes me unable to play bbc iplayer videos...still seeing restriction info

**Comment by trick77** [comment]
Dude, you really have to start reading the documentation from A-Z.
