### ISSUE TITLE
Netflix proxy error

### ISSUE THREAD

**Issue by pjbish** [trick77/dockerflix#34]
Thanks for this script. 

Does it still work for unblocking US Netflix since the recent purges ? I'm getting the dreaded "You seem to be using an unblocker or proxy."

I've configured this in an unusual way, so not sure if its my config or if Netflix has blocked everyone.

I VPN to a VPS which is running DNSMASQ with the config produced by your script, I have a separate VPS which is running the SNI proxy. Any DNS requests from the first box should get redirected to the SNI proxy box. All seems to work fine (no DNS leak , and I get the US Netflix catalogue), but I get the proxy message when trying to play content. 

Any ideas ?

**Comment by trick77** [comment]
Netflix really doesn't wan't you to access geo-restricted content. They have put in all kinds of checks to prevent this. It helps to use a VPS provider which has not YET been blacklisted, but that may be only temporary until those holes get closed down as well. I'd just forget about Netflix and use something like https://sickrage.github.io. It's not a 1:1 replacement though ;-)
