### ISSUE TITLE
Python Script

### ISSUE THREAD

**Issue by RobinGhost** [trick77/dockerflix#5]
I am have some serious problems trying to install python on my Atheros based dd-wrt router, do you by any chance have a work around for you python script. I have spent days trying to install python on my router.

Your effort is much appreciated ;)

Cheers

**Comment by ghost** [comment]
I can't help you with dd-wrt routers since I don't have one of those.

Are you trying to generate the dnsmasq config inside the router (are you trying to execute `gendns-conf.py` inside the router?)

**Comment by RobinGhost** [comment]
Yes I am trying to generate gendns-conf.py inside the router

**Comment by ghost** [comment]
You need to generate the config outside the router. Quoting from https://github.com/trick77/dockerflix#post-installation

> Generate a Dnsmasq configuration using:
> `python ./gendns-conf.py --remoteip <PUBLIC_IP_OF_YOUR_VPS_SERVER>`
> 
> This configuration has to be used in your home router (if it runs Dnsmasq for DNS resolution) or a Linux-based computer like the Raspberry Pi

Install python on your system and then execute `gendns-conf.py` which will generate a config file for dnsmasq. If dnsmasq is available on your router supply it the config file. Otherwise you need to install dnsmasq on a Linux machine in your LAN.

**Comment by RobinGhost** [comment]
Thanks for your advice,  when trick77 quoted 'This configuration has to be used in your home router' I assumed I had to install python and run the script from within my router, my mistake, but thanks anyway I managed to run the script on my pc.

My dd-wrt router has dnsmasq preinstalled. but does not have a folder etc/dnasmasq.d.
I am not exactly sure were I should be pasting the output from the python script.

Sorry I very new to dd-wrt,  maybe I should try an alternative firmware

**Comment by trick77** [comment]
Please let me know how to rephrase the paragraph to make things clearer. It got a bit short.
