### ISSUE TITLE
ABC on iOS and web browser not working

### ISSUE THREAD

**Issue by johngrasty** [trick77/dockerflix#6]
Hello,

Thanks for the great setup.I have used the previous version for 6 months. I have struggled to get ABC working though. I'm fairly comfortable debugging this sorts of issues, but this one has stumped me. Any hints as to where to look.

**Comment by trick77** [comment]
Hi,
The ABC iOS app is working fine on my iPad with Dockerflix.

Cheers,
Jan

**Comment by johngrasty** [comment]
Hmmm. Ok. I will have to take another look then. Thanks for the data point and the great setup.
