### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by Nobeernogman** [trick77/dockerflix#9]
Running the following commands:
wget -qO- https://get.docker.io/gpg | sudo apt-key add -
echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get install lxc-docker

This 4 steps going fine,  But the ./build.sh will give me some errors:
http://i.imgur.com/38dLuSa.png

I'm sure the error is the guy on the chair in front of his computer screen. But i dont know what i'm doint wrong.

@ Ubuntu 14.04 64-bit

**Comment by trick77** [comment]
In the instructions, I'm assuming everyone is using root when calling ./build.sh. If you use sudo, you have to make sure all Docker permissions have been setup for this user.

**Comment by Nobeernogman** [comment]
Sudo su / login with user root. the same output:

root@server:/home/server/dockerflix# ./build.sh
Sending build context to Docker daemon
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?

Driving me mad :-)

**Comment by trick77** [comment]
Well, obviously the Docker daemon is not running. Did you check the process list?

**Comment by Nobeernogman** [comment]
Guess my OpenVZ Virtualization is the problem..

**Comment by trick77** [comment]
I think OpenVZ prevents access to some things which Docker requires, like control groups, namespaces and probably network bridges as well.

**Comment by Nobeernogman** [comment]
Switched to KVM vps. Installed dockerflix like a breeze. But it wont work yet.

my steps:

wget -qO- https://get.docker.io/gpg | sudo apt-key add -
echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get install lxc-docker

./build.sh

docker run -d -p 80:80 -p 443:443 --restart=always --name dockerflix trick77/dockerflix

Dockerflix is running, checked with: docker ps -a

Error in chome: DNS_PROBE_FINISHED_BAD_CONFIG
I guess the destination of the IP table rules are not correct in my config. It's directing to 172.17.0.1 and that's not the external IP of my vps.

http://i.imgur.com/Ls1vcMb.png

I know my server is fully open now, but it's not working anway:P
How can i change the destination chain from 172.x to my external vps ip?

ifconfig info: http://i.imgur.com/t0gJCB3.png

Ps: "Star-red" this project! :)

**Comment by trick77** [comment]
What does your DNS setup look like? How did you set it up and where?

**Comment by Nobeernogman** [comment]
I just followed the steps from the dockerflix Readme.  And started the docker with : docker run -d -p 80:80 -p 443:443 --restart=always --name dockerflix trick77/dockerflix

Then set my vps ip as dns server on my windows machine, like i alway do.

**Comment by trick77** [comment]
Dockerflix does not provide a DNS server because an unsecured, recursive DNS resolver will always be used for DDoS attacks.
I'm quoting the README:
"This configuration has to be used in your home router (if it runs Dnsmasq for DNS resolution) or a Linux-based computer like the Raspberry Pi. Obviously, all DNS requests originating at home have to be resolved/forwarded through Dnsmasq from now on."
